=== mikhail-peredirey/Kitshop/src/main/resources/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.com/products"
           xmlns:tns="http://www.epam.com/products"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:element name="products" type="tns:Products"/>

    <xs:complexType name="Products">
        <xs:sequence>
            <xs:element name="product" type="tns:Product" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Product">
        <xs:all>
            <xs:element name="uuid" type="tns:UUID" minOccurs="0"/>
            <xs:element name="vendor" type="xs:string"/>
            <xs:element name="model" type="xs:string"/>
            <xs:element name="ports" type="xs:positiveInteger"/>
            <xs:element name="firmware" type="xs:string"/>
            <xs:element name="feature" type="xs:string"/>
            <xs:element name="manufactureDate" type="xs:date" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:simpleType name="UUID">
        <xs:restriction base="xs:string">
            <xs:pattern value="(?u)[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== mikhail-peredirey/Kitshop/src/main/resources/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<products xmlns="http://www.epam.com/products"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.epam.com/products http://www.epam.com/products/products.xsd">
    <product>
        <uuid>12345678-1234-1234-1234-123412341234</uuid>
        <vendor>Cisco</vendor>
        <model>2940</model>
        <ports>10</ports>
        <firmware>Cisc2940-K9</firmware>
        <feature>STP</feature>
        <manufactureDate>2015-01-01</manufactureDate>
    </product>
    <product>
        <vendor>D-Link</vendor>
        <model>DES-3200</model>
        <ports>18</ports>
        <firmware>DES-FIRMWARE-3.0.0</firmware>
        <feature>RSTP</feature>
    </product>
    <product>
        <vendor>HP</vendor>
        <model>ProCurve2910</model>
        <ports>48</ports>
        <firmware>HP-PROCURVE</firmware>
        <feature>LACP</feature>
    </product>
    <product>
        <vendor>Zyxel</vendor>
        <model>ES-2108</model>
        <ports>10</ports>
        <firmware>ZYXEL-FIRMWARE</firmware>
        <feature>SFP+</feature>
    </product>
</products>
